import Link from 'next/link';
import {allData,dayKey,fmt,mealSessions,sumMeals} from '@/lib/data';
export const dynamic='force-dynamic';
function relativeActivity(value?:string){if(!value)return '—';const d=new Date(value),diff=Date.now()-d.getTime(),time=d.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Moscow'}),dk=d.toLocaleDateString('sv-SE',{timeZone:'Europe/Moscow'}),now=new Date(),tk=now.toLocaleDateString('sv-SE',{timeZone:'Europe/Moscow'});if(dk===tk)return `Сегодня, ${time}`;if(diff<7*86400000)return `${Math.max(1,Math.floor(diff/86400000))} дн. назад`;return d.toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'Europe/Moscow'})}
function goalName(v:any){const s=String(v||'').toLowerCase();if(s.includes('loss')||s.includes('сниж')||s.includes('похуд'))return 'Снижение';if(s.includes('gain')||s.includes('набор'))return 'Набор';if(s.includes('maint')||s.includes('поддерж'))return 'Поддержание';return v||'Не указана'}
export default async function Page(){
 const {profiles,meals,logs,settings,subscriptions}=await allData();const today=dayKey();
 const settingMap=new Map((settings as any[]).map(x=>[Number(x.chat_id),x]));const subMap=new Map<number,any>();for(const x of subscriptions as any[]){if(!subMap.has(Number(x.chat_id)))subMap.set(Number(x.chat_id),x)}
 return <><div className="pageHead"><div><p>AI‑Nutrition / Админка</p><h1>Клиенты</h1><span>Профили, цели, тарифы и реальная активность</span></div></div><section className="card tableCard"><div className="tableHead clientsGridV2"><span>Клиент</span><span>Цель</span><span>Тариф</span><span>Сегодня</span><span>Всего</span><span>Активность</span></div>{profiles.map(p=>{const id=Number(p.telegram_id),pm=meals.filter(m=>m.chat_id===id),t=pm.filter(m=>m.eaten_day===today),todaySessions=mealSessions(t),allSessions=mealSessions(pm),s=sumMeals(t),last=[pm[0]?.eaten_at,...logs.filter((l:any)=>Number(l.chat_id)===id).slice(0,1).map((x:any)=>x.created_at)].filter(Boolean).sort().reverse()[0] as string|undefined,st:any=settingMap.get(id),sub=subMap.get(id);return <Link href={`/admin/clients/${id}`} className="tableRow clientsGridV2" key={p.id}><div><b>{p.first_name||'Без имени'}</b><small>{p.username?'@'+p.username:String(id)}</small></div><div><span className="goalPill">{goalName(st?.goal)}</span></div><div><span className={`planPill ${sub?.plan||'none'}`}>{sub?.status==='active'?String(sub.plan).toUpperCase():'—'}</span></div><div><b>{fmt(s.kcal)} ккал</b><small>{todaySessions.length} приём.</small></div><div>{allSessions.length} приём.</div><div className={last&&Date.now()-new Date(last).getTime()>3*86400000?'stale':''}>{relativeActivity(last)}</div></Link>})}</section></>
}
