import TelegramAvatar from "@/components/TelegramAvatar";
import Link from "next/link";
import {AlertTriangle,CalendarDays,MessageSquare,Scale,Target,TrendingUp,Utensils} from "lucide-react";
import FoodIcon from "@/components/FoodIcon";
import AdminSubscriptionControl from "@/components/AdminSubscriptionControl";
import AdminRoleControl from "@/components/AdminRoleControl";
import {getSupabaseAdmin} from "@/lib/supabase-admin";
import {adminClientOverviewData,dayKey,fmt,goalKind,mealDay,mealSessions,pluralMeals,sumMeals} from "@/lib/data";
import AdminBadge from "@/components/AdminBadge";
export const dynamic="force-dynamic";
function prettyDay(day:string){return new Date(`${day}T12:00:00`).toLocaleDateString("ru-RU",{day:"numeric",month:"short",weekday:"short"})}
function pct(v:number,t:number){return t?Math.min(100,Math.round(v/t*100)):0}
export default async function Page({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{day?:string}>}){
 const {id}=await params,qp=await searchParams,chatId=Number(id),d=await adminClientOverviewData(chatId);if(!d.profile)return <div>Клиент не найден</div>;
 const supabase=getSupabaseAdmin();
 const {data:adminRole}=await supabase.from("admin_users").select("is_active").eq("chat_id",chatId).maybeSingle();
 const isSiteAdmin=adminRole?.is_active===true;
 const today=dayKey(),selectedDay=qp.day&&/^\d{4}-\d{2}-\d{2}$/.test(qp.day)?qp.day:today;
 const byDay=new Map<string,typeof d.meals>();for(const m of d.meals){const day=mealDay(m);if(!byDay.has(day))byDay.set(day,[]);byDay.get(day)!.push(m)}
 const selectedMeals=byDay.get(selectedDay)||[],selectedSum=sumMeals(selectedMeals),selectedSessions=mealSessions(selectedMeals),st:any=d.settings||{};
 const target=Number(st.kcal_target||0),protTarget=Number(st.protein_target||st.protein_target_g||st.prot_target||0),fatTarget=Number(st.fat_target||st.fat_target_g||0),carbTarget=Number(st.carb_target||st.carb_target_g||0),cw=Number(st.current_weight_kg||d.weights?.[0]?.weight_kg||0),tw=Number(st.target_weight_kg||0);
 const recentDays=Array.from({length:14},(_,i)=>{const date=new Date();date.setDate(date.getDate()-(13-i));const day=dayKey(date),rows=byDay.get(day)||[];return{day,total:sumMeals(rows),sessions:mealSessions(rows).length}}),week=recentDays.slice(-7),activeWeek=week.filter(x=>x.sessions>0),avg7=activeWeek.length?Math.round(activeWeek.reduce((a,x)=>a+x.total.kcal,0)/activeWeek.length):0,activeDays=activeWeek.length,proteinLow=protTarget?week.filter(x=>x.total.prot>0&&x.total.prot<protTarget*.75).length:0,max=Math.max(target,1,...week.map(x=>x.total.kcal));
 const observations:string[]=[];if(target)observations.push(`Среднее за 7 дней: ${avg7} ккал — ${Math.round(avg7/target*100)}% от цели.`);if(proteinLow>=3)observations.push(`Белок ниже 75% нормы в ${proteinLow} днях из 7.`);if(activeDays<5)observations.push(`Питание зафиксировано в ${activeDays} днях из 7.`);if(!d.weights.length)observations.push("Вес ещё не вносился.");if(d.unread)observations.push(`${d.unread} непрочитанных сообщений.`);if(!observations.length)observations.push("Выраженных отклонений за 7 дней нет.");
 return <><Link className="back" href="/admin/clients">← Назад к клиентам</Link><div className="clientHeroV3"><TelegramAvatar profile={d.profile} size="large"/><div className="clientHeroInfo"><div className="clientNameLine"><h1>{d.profile.first_name||"Без имени"}{isSiteAdmin&&<AdminBadge compact={false}/>}</h1><span className={`planPill ${d.subscription?.plan||"none"}`}>{d.subscription?.status==="active"?String(d.subscription.plan).toUpperCase():"БЕЗ ПОДПИСКИ"}</span></div><p>{d.profile.username?`@${d.profile.username}`:`Telegram ${chatId}`}</p>{d.profile.avatar_updated_at&&<small className="telegramSyncMeta">Telegram: {new Date(d.profile.avatar_updated_at).toLocaleString("ru-RU",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}</small>}<div className="clientTags"><span><Target size={13}/>{goalKind(st.goal)}</span>{cw>0&&<span><Scale size={13}/>{fmt(cw,1)} кг</span>}<span><CalendarDays size={13}/>{activeDays}/7 дней</span></div></div><div className="clientHeroActions"><Link className="primary compactBtn" href={`/admin/dialogs?chat=${chatId}`}><MessageSquare size={16}/>Написать{d.unread?` (${d.unread})`:""}</Link><Link className="secondaryBtn" href="#nutrition"><Utensils size={16}/>Рацион</Link></div></div>
 <section className="card top"><div className="sectionTitleRow"><div><h2>Управление подпиской</h2><span className="muted">Изменение тарифа сразу меняет доступ клиента.</span></div></div><AdminSubscriptionControl chatId={chatId} currentPlan={d.subscription?.status==="active"?(d.subscription?.plan as "basic"|"premium"):"none"}/></section>
 <section className="card top"><div className="sectionTitleRow"><div><h2>Роль на сайте</h2><span className="muted">Доступ к административной панели назначается отдельно от тарифа.</span></div></div><AdminRoleControl chatId={chatId} current={isSiteAdmin}/></section>
 <div className="clientOverviewGrid"><section className="card nutritionRingCard"><div className="sectionTitleRow"><div><h2>Питание — {prettyDay(selectedDay)}</h2><span className="muted">{selectedSessions.length} {pluralMeals(selectedSessions.length)}</span></div></div><div className="ringWrap"><div className="calorieRing" style={{"--progress":`${pct(selectedSum.kcal,target)}%`} as React.CSSProperties}><b>{fmt(selectedSum.kcal)}</b><span>/ {target?fmt(target):"—"} ккал</span></div></div><div className="macroStrip"><span><b>{fmt(selectedSum.prot,1)} г</b>Белки<small>{protTarget?`${pct(selectedSum.prot,protTarget)}%`:""}</small></span><span><b>{fmt(selectedSum.fat,1)} г</b>Жиры<small>{fatTarget?`${pct(selectedSum.fat,fatTarget)}%`:""}</small></span><span><b>{fmt(selectedSum.carb,1)} г</b>Углеводы<small>{carbTarget?`${pct(selectedSum.carb,carbTarget)}%`:""}</small></span></div></section>
 <section className="card clientFactsCard"><h2>Профиль</h2><div className="clientFacts"><div className="clientFact"><span>Цель</span><b>{goalKind(st.goal)}</b></div><div className="clientFact"><span>Калории</span><b>{target?`${fmt(target)} ккал`:"—"}</b></div><div className="clientFact"><span>Вес</span><b>{cw?`${fmt(cw,1)} кг`:"—"}</b></div><div className="clientFact"><span>Цель веса</span><b>{tw?`${fmt(tw,1)} кг`:"—"}</b></div><div className="clientFact"><span>Рост</span><b>{st.height_cm?`${st.height_cm} см`:"—"}</b></div><div className="clientFact"><span>Активность</span><b>{st.activity_level||"—"}</b></div></div>{cw>0&&tw>0&&<div className="weightTarget">До цели: <b>{fmt(Math.abs(cw-tw),1)} кг</b></div>}</section>
 <section className="card aiObservations"><div className="sectionTitleRow"><div><h2>Сигналы</h2><span className="muted">Только полезные отклонения</span></div><TrendingUp size={19}/></div><div>{observations.map((x,i)=><p key={i}><AlertTriangle size={15}/><span>{x}</span></p>)}</div></section></div>
 <section className="card top"><div className="sectionTitleRow"><div><h2>Календарь · 14 дней</h2><span className="muted">Открывай день без загрузки всей истории</span></div></div><div className="clientCalendar">{recentDays.map(x=><Link href={`/admin/clients/${chatId}?day=${x.day}#nutrition`} className={`${x.day===selectedDay?"active ":""}${x.sessions?"hasData":""}`} key={x.day}><span>{prettyDay(x.day).split(",")[0]}</span><b>{new Date(`${x.day}T12:00:00`).getDate()}</b><small>{x.sessions?`${x.sessions} ${pluralMeals(x.sessions)}`:"—"}</small></Link>)}</div></section>
 <div className="clientDetailsGrid top"><section className="card"><div className="sectionTitleRow"><div><h2>Калории · 7 дней</h2><span className="muted">Цель пунктиром</span></div><b className="chartAverage">Ø {avg7}</b></div><div className="clientWeekChart">{week.map(x=><div className="clientWeekCol" key={x.day}><span>{Math.round(x.total.kcal)||""}</span><div className="clientWeekTrack"><i style={{height:`${Math.max(4,x.total.kcal/max*100)}%`}}/>{target>0&&<em style={{bottom:`${Math.min(100,target/max*100)}%`}}/>}</div><small>{new Date(`${x.day}T12:00:00`).toLocaleDateString("ru-RU",{weekday:"short"})}</small></div>)}</div></section><section className="card"><div className="sectionTitleRow"><div><h2>Вес</h2><span className="muted">Последние измерения</span></div></div>{d.weights.length?<div className="weightHistory">{d.weights.slice(0,8).map((w:any)=><div className="row" key={w.id}><span>{new Date(w.measured_at).toLocaleDateString("ru-RU",{day:"2-digit",month:"short"})}</span><b>{fmt(w.weight_kg,1)} кг</b></div>)}</div>:<div className="emptyState"><Scale/><b>Нет измерений</b></div>}</section></div>
 <section className="card top" id="nutrition"><div className="sectionTitleRow"><div><h2>Приёмы — {prettyDay(selectedDay)}</h2><span className="muted">{selectedMeals.length} позиций · {selectedSessions.length} {pluralMeals(selectedSessions.length)}</span></div></div>{selectedSessions.length?<div className="visualMeals">{selectedSessions.map(session=><article className="visualMealSession" key={session.key}><header><div><b>{session.time}</b><span>{session.meals.length} поз.</span></div><strong>{fmt(session.total.kcal)} ккал</strong></header><div>{session.meals.map(m=><div className="visualMealItem" key={m.id}><i><FoodIcon dish={m.dish}/></i><span><b>{m.dish}</b><small>{fmt(m.grams)} г · Б {fmt(m.prot,1)} · Ж {fmt(m.fat,1)} · У {fmt(m.carb,1)}</small></span><strong>{fmt(m.kcal)} ккал</strong></div>)}</div></article>)}</div>:<div className="emptyState"><Utensils/><b>Нет записей</b><span>Выбери другой день.</span></div>}</section></>;
}