import Link from "next/link";
import {Check,Crown,Sparkles,Utensils,TrendingUp,Headphones,Camera,BrainCircuit} from "lucide-react";
import {requireClient} from "@/lib/auth";
import {clientProfileData,fmt} from "@/lib/data";
export const dynamic="force-dynamic";
const basic=["Трекер питания по фото и вручную","КБЖУ и история приёмов","Дневная цель и остаток КБЖУ","Базовая динамика веса и калорий","Профиль, цель и нормы","Поддержка по работе сервиса"];
const premium=["Всё из Basic","AI‑сводка дня с рекомендациями","Умные подсказки следующего приёма","Расширенный анализ 7/14 дней","Сигналы по белку, калориям и регулярности","Приоритетное распознавание сложных продуктов","Персональные недельные выводы и тренды","Приоритетная поддержка"];
export default async function Page(){const s=await requireClient(),d=await clientProfileData(s.chatId!),sub:any=d.subscription||{},active=sub.status==="active";return <><div className="pageHead"><div><p>Тариф</p><h1>Подписка</h1><span>Трекер остаётся простым, Premium добавляет аналитику и персонализацию.</span></div></div><section className="currentPlanStrip"><div><span>Текущий тариф</span><b>{active?String(sub.plan||"").toUpperCase():"Без подписки"}</b></div>{active&&sub.ends_at&&<small>Активна до {new Date(sub.ends_at).toLocaleDateString("ru-RU",{day:"numeric",month:"long"})}</small>}</section><div className="plansGrid top"><Plan icon={<Utensils/>} name="Basic" note="Всё необходимое для ежедневного контроля" features={basic} tone="basic"/><Plan icon={<Crown/>} name="Premium" note="Трекер + персональная аналитика и AI‑сопровождение" features={premium} tone="premium" popular/></div><section className="card top planPrinciples"><div><Camera/><span><b>Basic — инструмент</b><small>Быстро фиксируй питание и смотри факты.</small></span></div><div><BrainCircuit/><span><b>Premium — помощник</b><small>Сервис не только хранит данные, но и помогает понять, что делать дальше.</small></span></div><div><TrendingUp/><span><b>Без перегруза</b><small>Премиум-функции показываются только там, где дают пользу.</small></span></div><div><Headphones/><span><b>Живая поддержка</b><small>Важные вопросы можно передать человеку.</small></span></div></section></>}
function Plan({icon,name,note,features,tone,popular}:{icon:React.ReactNode;name:string;note:string;features:string[];tone:string;popular?:boolean}){return <section className={`planCard ${tone}`}>{popular&&<em>РЕКОМЕНДУЕМ</em>}<div className="planCardHead"><i>{icon}</i><div><h2>{name}</h2><p>{note}</p></div></div><div className="planFeatures">{features.map(x=><div key={x}><Check size={15}/><span>{x}</span></div>)}</div><Link className={popular?"primary planCta":"secondaryBtn planCta"} href="/client/support">{popular?"Подключить Premium":"Подключить Basic"}</Link></section>}
