import Link from "next/link";
import {Check,Crown,BrainCircuit,Camera,ChartNoAxesCombined,MessageCircleMore,ShoppingBasket,Sparkles,Target,UtensilsCrossed} from "lucide-react";
import {requireClient} from "@/lib/auth";
import {clientProfileData,subscriptionLifecycleData} from "@/lib/data";
export const dynamic="force-dynamic";
const basic=["Распознавание еды по фото","Ручной ввод и /day","КБЖУ и дневник питания","Сегодняшний остаток КБЖУ","История и базовый прогресс","Вес и личный профиль"];
const premium=["Всё из Basic","Персональный AI‑нутрициолог","Ежедневный план питания","Рекомендации следующего приёма","Food Memory — знает твои привычные продукты","«Я в магазине / ресторане / нет времени»","Умные подсказки в течение дня","Недельный стратегический разбор","Анализ веса и тренда 7/14 дней","Предложения по корректировке целей","Комментарии после приёмов пищи","Приоритетная поддержка"];
export default async function Page(){const a=await requireClient(),d=await clientProfileData(a.chatId!),s:any=d.subscription||{},premium=s.status==="active"&&s.plan==="premium"&&(!s.ends_at||new Date(s.ends_at)>new Date());return <><div className="pageHead"><div><p>TeddY</p><h1>Выбери уровень сопровождения</h1><span>Basic считает. Premium думает вместе с тобой и помогает действовать.</span></div></div>{life&&<section className="subscriptionLifecycleBar"><div><small>Текущий доступ</small><b>{life.plan==="premium"?"Premium":"Basic"} · {life.state}</b><span>{life.current_period_end?`до ${new Date(life.current_period_end).toLocaleDateString("ru-RU")}`:"без указанного срока"}</span></div>{life.plan==="premium"&&["trial","active","grace"].includes(life.state)&&!life.cancel_at_period_end?<form action="/api/subscription/lifecycle" method="post"><button className="secondaryBtn" name="action" value="cancel">Отключить автопродление</button></form>:null}</section>}
{premium&&<Link href="/client/coach" className="premiumActiveBanner"><Crown/><span><small>Premium активен</small><b>Открыть персонального нутрициолога</b></span>→</Link>}
{!premium&&!life&&<form action="/api/subscription/lifecycle" method="post" className="trialBanner"><div><small>7 дней</small><b>Попробовать TeddY Premium</b><span>Персональный Coach, планы, рекомендации и недельная стратегия.</span></div><button className="primary" name="action" value="trial">Начать trial</button></form>}<div className="plansGrid premiumComparison top"><Plan name="Basic" sub="Трекер питания" desc="Для тех, кому нужен быстрый и удобный контроль рациона." features={basic}/><Plan name="Premium" sub="AI‑нутрициолог" desc="Для тех, кто хочет не считать самому, а получать персональную стратегию каждый день." features={premium} premium/></div><section className="premiumDifference top"><div><Camera/><b>Basic фиксирует</b><span>Что и сколько ты съел.</span></div><div><BrainCircuit/><b>Premium понимает</b><span>Что это значит именно для твоей цели.</span></div><div><Target/><b>Premium корректирует</b><span>Подсказывает следующий шаг и замечает тренды.</span></div><div><MessageCircleMore/><b>Premium сопровождает</b><span>Сам выходит на связь, когда это действительно полезно.</span></div></section><section className="card top premiumExamples"><div className="sectionTitleRow"><div><h2>За что платят в Premium</h2><span className="muted">Не дополнительные графики, а экономия решений каждый день</span></div><Sparkles/></div><div><Example icon={<ShoppingBasket/>} q="Я в SPAR. Что купить?" a="TeddY знает, сколько осталось белка и калорий, и собирает конкретный набор продуктов."/><Example icon={<UtensilsCrossed/>} q="Что поесть вечером?" a="Учитывает сегодняшний рацион, цель, вес и привычные продукты — а не выдаёт общий совет."/><Example icon={<ChartNoAxesCombined/>} q="Вес стоит уже две недели" a="Сопоставляет вес и средний рацион и предлагает изменение стратегии, которое ты подтверждаешь сам."/></div></section></>}
function Plan({name,sub,desc,features,premium}:{name:string;sub:string;desc:string;features:string[];premium?:boolean}){return <section className={`planCard ${premium?"premium":"basic"}`}>{premium&&<em>ПОЛНОЕ СОПРОВОЖДЕНИЕ</em>}<div className="planCardHead"><i>{premium?<Crown/>:<Camera/>}</i><div><small>{sub}</small><h2>{name}</h2><p>{desc}</p></div></div><div className="planFeatures">{features.map(x=><div key={x}><Check size={15}/><span>{x}</span></div>)}</div><Link className={premium?"primary planCta":"secondaryBtn planCta"} href={premium?"/client/onboarding":"/client/nutrition"}>{premium?"Настроить Premium":"Открыть трекер"}</Link></section>}
function Example({icon,q,a}:{icon:React.ReactNode;q:string;a:string}){return <article><i>{icon}</i><span><b>{q}</b><p>{a}</p></span></article>}
