import fs from "fs";import path from "path";
let pass=0,fail=0;const ok=(name,cond)=>{if(cond){pass++;console.log("PASS",name)}else{fail++;console.error("FAIL",name)}};
const read=p=>fs.readFileSync(p,"utf8"),J=p=>JSON.parse(read(p));
const n8=path.resolve("n8n/v19"),files=fs.readdirSync(n8).filter(x=>x.endsWith(".json"));
const all=files.map(f=>[f,J(path.join(n8,f))]),ids=new Set(all.map(([,w])=>w.id));
ok("release has workflows",files.length>=10);
let tg=[];for(const [f,w] of all)for(const n of w.nodes||[])if(n.type==="n8n-nodes-base.telegramTrigger")tg.push([f,n.name]);
ok("single Telegram ingress",tg.length===1);
ok("ingress is V20",tg[0]?.[0]==="AI_Nutrition_Telegram_Ingress_v20.json");
for(const [f,w] of all){const names=new Set((w.nodes||[]).map(n=>n.name));let good=true;for(const [src,m] of Object.entries(w.connections||{})){if(!names.has(src))good=false;for(const bs of Object.values(m))for(const b of bs)for(const c of b)if(!names.has(c.node))good=false}ok(`graph ${f}`,good)}
let refs=true;for(const [,w] of all)for(const n of w.nodes||[])if(n.type==="n8n-nodes-base.executeWorkflow"){const x=n.parameters?.workflowId,id=typeof x==="object"?x.value:x;if(id&&!ids.has(id))refs=false}ok("all included subworkflow refs resolve",refs);
const raw=files.map(f=>read(path.join(n8,f))).join("\n");
ok("no embedded Telegram token",!/\b\d{8,10}:[A-Za-z0-9_-]{30,}\b/.test(raw));
ok("no embedded JWT",!/eyJ[A-Za-z0-9_-]{20,}\.eyJ[A-Za-z0-9_-]{20,}\./.test(raw));
ok("callback has no stale Telegram Trigger expression",!read(path.join(n8,"tg_callbacks_v18_confidence_learning.json")).includes("Telegram Trigger"));
ok("callback uses personal overrides",read(path.join(n8,"tg_callbacks_v18_confidence_learning.json")).includes("GET Personal Food Overrides"));
ok("callback logs recognition confidence",read(path.join(n8,"tg_callbacks_v18_confidence_learning.json")).includes("LOG Recognition Confidence"));
ok("context uses V20 cached RPC",read(path.join(n8,"AI_Nutrition_Context_Engine_v20.json")).includes("get_nutrition_context_v20"));
ok("Premium coach has budget guard",read(path.join(n8,"AI_Nutrition_Premium_Coach_v5_Smooth.json")).includes("AI Budget Guard"));
ok("Premium coach has circuit breaker",read(path.join(n8,"AI_Nutrition_Premium_Coach_v5_Smooth.json")).includes("AI Circuit Check"));
ok("Premium coach has concurrency slot",read(path.join(n8,"AI_Nutrition_Premium_Coach_v5_Smooth.json")).includes("Claim AI Slot"));
ok("Premium coach has fallback",read(path.join(n8,"AI_Nutrition_Premium_Coach_v5_Smooth.json")).includes("Deterministic Fallback"));
ok("Premium coach consumes coach knowledge",read(path.join(n8,"AI_Nutrition_Premium_Coach_v5_Smooth.json")).includes("coach_knowledge"));
const sql=read("supabase/migrations/012_v20_product_intelligence.sql");
for(const t of ["recognition_events","client_food_overrides","correction_events","processing_jobs","service_circuit_breakers","replay_events","subscription_lifecycle","premium_onboarding","coach_sources","coach_knowledge","adaptive_coach_profile","ai_concurrency_leases"])ok(`SQL table ${t}`,sql.includes(`table if not exists ${t}`));
for(const fn of ["get_nutrition_context_v20","claim_ai_slot","release_ai_slot","nutrition_guardrails","refresh_adaptive_coach","enqueue_job","claim_jobs","circuit_allows","subscription_entitlement"])ok(`SQL function ${fn}`,sql.includes(`function ${fn}`));
const score=(f,p,n,cap=false)=>Math.max(0,Math.min(1,f*.45+p*.30+n*.25+(cap?.05:0)));
ok("high confidence passes",score(.95,.9,.95,true)>=.68);
ok("weak portion requires review",score(.8,.15,.65,false)<.68);
ok("caption improves confidence",score(.65,.7,.75,true)>score(.65,.7,.75,false));
const entitlement=(plan,state,feat)=>{if(!plan)return ["tracking","today","history","profile"].includes(feat);if(!["trial","active","grace"].includes(state))return ["tracking","today","history","profile"].includes(feat);if(plan==="premium")return true;return ["tracking","today","history","profile","basic_progress"].includes(feat)};
ok("Basic cannot use premium recommend",!entitlement("basic","active","recommend"));
ok("Premium can recommend",entitlement("premium","active","recommend"));
ok("Premium trial can recommend",entitlement("premium","trial","recommend"));
ok("Expired premium loses recommend",!entitlement("premium","expired","recommend"));
const pacing=(e,t,h)=>{const share=t?e/t:0,expected=Math.min(.95,Math.max(.12,(h-7)/15));return Math.abs(share-expected)<.18?"ok":share<expected?"behind":"ahead"};
ok("day pacing normal midday",pacing(1200,3000,14)==="ok");
ok("day pacing late underfed",pacing(900,3000,21)==="behind");
ok("day pacing ahead",pacing(2500,3000,15)==="ahead");
for(const p of ["app/client/onboarding/page.tsx","app/admin/knowledge/page.tsx","app/admin/replay/page.tsx","app/admin/system/page.tsx"])ok(`page ${p}`,fs.existsSync(p));
ok("knowledge seed has uploaded sources",read("supabase/migrations/013_coach_video_sources.sql").includes("970474402340444962(1).MP4"));
ok("knowledge sugar thesis source-verified",read("supabase/migrations/013_coach_video_sources.sql").includes("'verified'"));
ok("trainer technique thesis seeded",read("supabase/migrations/013_coach_video_sources.sql").includes("training_technique"));
console.log(`\nV20 TESTS: ${pass} passed, ${fail} failed`);if(fail)process.exit(1);
