-- Legacy migration intentionally disabled.
-- The production Supabase already contains the bot tables:
-- profiles, meals, meals_draft, digests, chat_logs.
-- Do not recreate them from the old website prototype because its schema differed from the bot schema.
-- Apply 002_portal.sql only.
